# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./postgres-data:/var/lib/pstgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080